// This file was generated by counterfeiter
package cephfakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/cephbroker/cephbrokerlocal"
	"github.com/cloudfoundry-incubator/cephbroker/model"
	"github.com/pivotal-golang/lager"
)

type FakeController struct {
	GetCatalogStub        func(logger lager.Logger) (model.Catalog, error)
	getCatalogMutex       sync.RWMutex
	getCatalogArgsForCall []struct {
		logger lager.Logger
	}
	getCatalogReturns struct {
		result1 model.Catalog
		result2 error
	}
	CreateServiceInstanceStub        func(logger lager.Logger, serverInstanceId string, instance model.ServiceInstance) (model.CreateServiceInstanceResponse, error)
	createServiceInstanceMutex       sync.RWMutex
	createServiceInstanceArgsForCall []struct {
		logger           lager.Logger
		serverInstanceId string
		instance         model.ServiceInstance
	}
	createServiceInstanceReturns struct {
		result1 model.CreateServiceInstanceResponse
		result2 error
	}
	ServiceInstanceExistsStub        func(logger lager.Logger, serviceInstanceId string) bool
	serviceInstanceExistsMutex       sync.RWMutex
	serviceInstanceExistsArgsForCall []struct {
		logger            lager.Logger
		serviceInstanceId string
	}
	serviceInstanceExistsReturns struct {
		result1 bool
	}
	ServiceInstancePropertiesMatchStub        func(logger lager.Logger, serviceInstanceId string, instance model.ServiceInstance) bool
	serviceInstancePropertiesMatchMutex       sync.RWMutex
	serviceInstancePropertiesMatchArgsForCall []struct {
		logger            lager.Logger
		serviceInstanceId string
		instance          model.ServiceInstance
	}
	serviceInstancePropertiesMatchReturns struct {
		result1 bool
	}
	DeleteServiceInstanceStub        func(logger lager.Logger, serviceInstanceId string) error
	deleteServiceInstanceMutex       sync.RWMutex
	deleteServiceInstanceArgsForCall []struct {
		logger            lager.Logger
		serviceInstanceId string
	}
	deleteServiceInstanceReturns struct {
		result1 error
	}
}

func (fake *FakeController) GetCatalog(logger lager.Logger) (model.Catalog, error) {
	fake.getCatalogMutex.Lock()
	fake.getCatalogArgsForCall = append(fake.getCatalogArgsForCall, struct {
		logger lager.Logger
	}{logger})
	fake.getCatalogMutex.Unlock()
	if fake.GetCatalogStub != nil {
		return fake.GetCatalogStub(logger)
	} else {
		return fake.getCatalogReturns.result1, fake.getCatalogReturns.result2
	}
}

func (fake *FakeController) GetCatalogCallCount() int {
	fake.getCatalogMutex.RLock()
	defer fake.getCatalogMutex.RUnlock()
	return len(fake.getCatalogArgsForCall)
}

func (fake *FakeController) GetCatalogArgsForCall(i int) lager.Logger {
	fake.getCatalogMutex.RLock()
	defer fake.getCatalogMutex.RUnlock()
	return fake.getCatalogArgsForCall[i].logger
}

func (fake *FakeController) GetCatalogReturns(result1 model.Catalog, result2 error) {
	fake.GetCatalogStub = nil
	fake.getCatalogReturns = struct {
		result1 model.Catalog
		result2 error
	}{result1, result2}
}

func (fake *FakeController) CreateServiceInstance(logger lager.Logger, serverInstanceId string, instance model.ServiceInstance) (model.CreateServiceInstanceResponse, error) {
	fake.createServiceInstanceMutex.Lock()
	fake.createServiceInstanceArgsForCall = append(fake.createServiceInstanceArgsForCall, struct {
		logger           lager.Logger
		serverInstanceId string
		instance         model.ServiceInstance
	}{logger, serverInstanceId, instance})
	fake.createServiceInstanceMutex.Unlock()
	if fake.CreateServiceInstanceStub != nil {
		return fake.CreateServiceInstanceStub(logger, serverInstanceId, instance)
	} else {
		return fake.createServiceInstanceReturns.result1, fake.createServiceInstanceReturns.result2
	}
}

func (fake *FakeController) CreateServiceInstanceCallCount() int {
	fake.createServiceInstanceMutex.RLock()
	defer fake.createServiceInstanceMutex.RUnlock()
	return len(fake.createServiceInstanceArgsForCall)
}

func (fake *FakeController) CreateServiceInstanceArgsForCall(i int) (lager.Logger, string, model.ServiceInstance) {
	fake.createServiceInstanceMutex.RLock()
	defer fake.createServiceInstanceMutex.RUnlock()
	return fake.createServiceInstanceArgsForCall[i].logger, fake.createServiceInstanceArgsForCall[i].serverInstanceId, fake.createServiceInstanceArgsForCall[i].instance
}

func (fake *FakeController) CreateServiceInstanceReturns(result1 model.CreateServiceInstanceResponse, result2 error) {
	fake.CreateServiceInstanceStub = nil
	fake.createServiceInstanceReturns = struct {
		result1 model.CreateServiceInstanceResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeController) ServiceInstanceExists(logger lager.Logger, serviceInstanceId string) bool {
	fake.serviceInstanceExistsMutex.Lock()
	fake.serviceInstanceExistsArgsForCall = append(fake.serviceInstanceExistsArgsForCall, struct {
		logger            lager.Logger
		serviceInstanceId string
	}{logger, serviceInstanceId})
	fake.serviceInstanceExistsMutex.Unlock()
	if fake.ServiceInstanceExistsStub != nil {
		return fake.ServiceInstanceExistsStub(logger, serviceInstanceId)
	} else {
		return fake.serviceInstanceExistsReturns.result1
	}
}

func (fake *FakeController) ServiceInstanceExistsCallCount() int {
	fake.serviceInstanceExistsMutex.RLock()
	defer fake.serviceInstanceExistsMutex.RUnlock()
	return len(fake.serviceInstanceExistsArgsForCall)
}

func (fake *FakeController) ServiceInstanceExistsArgsForCall(i int) (lager.Logger, string) {
	fake.serviceInstanceExistsMutex.RLock()
	defer fake.serviceInstanceExistsMutex.RUnlock()
	return fake.serviceInstanceExistsArgsForCall[i].logger, fake.serviceInstanceExistsArgsForCall[i].serviceInstanceId
}

func (fake *FakeController) ServiceInstanceExistsReturns(result1 bool) {
	fake.ServiceInstanceExistsStub = nil
	fake.serviceInstanceExistsReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeController) ServiceInstancePropertiesMatch(logger lager.Logger, serviceInstanceId string, instance model.ServiceInstance) bool {
	fake.serviceInstancePropertiesMatchMutex.Lock()
	fake.serviceInstancePropertiesMatchArgsForCall = append(fake.serviceInstancePropertiesMatchArgsForCall, struct {
		logger            lager.Logger
		serviceInstanceId string
		instance          model.ServiceInstance
	}{logger, serviceInstanceId, instance})
	fake.serviceInstancePropertiesMatchMutex.Unlock()
	if fake.ServiceInstancePropertiesMatchStub != nil {
		return fake.ServiceInstancePropertiesMatchStub(logger, serviceInstanceId, instance)
	} else {
		return fake.serviceInstancePropertiesMatchReturns.result1
	}
}

func (fake *FakeController) ServiceInstancePropertiesMatchCallCount() int {
	fake.serviceInstancePropertiesMatchMutex.RLock()
	defer fake.serviceInstancePropertiesMatchMutex.RUnlock()
	return len(fake.serviceInstancePropertiesMatchArgsForCall)
}

func (fake *FakeController) ServiceInstancePropertiesMatchArgsForCall(i int) (lager.Logger, string, model.ServiceInstance) {
	fake.serviceInstancePropertiesMatchMutex.RLock()
	defer fake.serviceInstancePropertiesMatchMutex.RUnlock()
	return fake.serviceInstancePropertiesMatchArgsForCall[i].logger, fake.serviceInstancePropertiesMatchArgsForCall[i].serviceInstanceId, fake.serviceInstancePropertiesMatchArgsForCall[i].instance
}

func (fake *FakeController) ServiceInstancePropertiesMatchReturns(result1 bool) {
	fake.ServiceInstancePropertiesMatchStub = nil
	fake.serviceInstancePropertiesMatchReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeController) DeleteServiceInstance(logger lager.Logger, serviceInstanceId string) error {
	fake.deleteServiceInstanceMutex.Lock()
	fake.deleteServiceInstanceArgsForCall = append(fake.deleteServiceInstanceArgsForCall, struct {
		logger            lager.Logger
		serviceInstanceId string
	}{logger, serviceInstanceId})
	fake.deleteServiceInstanceMutex.Unlock()
	if fake.DeleteServiceInstanceStub != nil {
		return fake.DeleteServiceInstanceStub(logger, serviceInstanceId)
	} else {
		return fake.deleteServiceInstanceReturns.result1
	}
}

func (fake *FakeController) DeleteServiceInstanceCallCount() int {
	fake.deleteServiceInstanceMutex.RLock()
	defer fake.deleteServiceInstanceMutex.RUnlock()
	return len(fake.deleteServiceInstanceArgsForCall)
}

func (fake *FakeController) DeleteServiceInstanceArgsForCall(i int) (lager.Logger, string) {
	fake.deleteServiceInstanceMutex.RLock()
	defer fake.deleteServiceInstanceMutex.RUnlock()
	return fake.deleteServiceInstanceArgsForCall[i].logger, fake.deleteServiceInstanceArgsForCall[i].serviceInstanceId
}

func (fake *FakeController) DeleteServiceInstanceReturns(result1 error) {
	fake.DeleteServiceInstanceStub = nil
	fake.deleteServiceInstanceReturns = struct {
		result1 error
	}{result1}
}

var _ cephbrokerlocal.Controller = new(FakeController)
